// NextJs
import Head from "next/head";
// Mui Components
import Box from '@mui/material/Box';
// Components
import Footer from './components/footer/Footer';
import Navbar from './components/navbar/Navbar';
import './globals.css'
// Theme
import ThemeRegistry from './utils/theme/theme';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const siteUrl = "https://andrea-pot-osteopathe.vercel.app/"


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Head>
          <title>Andréa Pot - Ostéopathe à Plounéour-Brignogan-Plages</title>
          <meta name="description" content="Andréa Pot, ostéopathe D.O à Maison médicale de la Baie. Spécialisée dans le traitement et la prévention des troubles musculo-squelettiques." />
          <meta name="keywords" content="Andréa Pot, ostéopathe, Maison médicale de la Baie, Plounéour-Brignogan-Plages, traitement musculo-squelettique, prévention santé" />
          <meta property="og:title" content="Andréa Pot - Ostéopathe à Plounéour-Brignogan-Plages" />
          <meta property="og:description" content="Andréa Pot, ostéopathe D.O à Maison médicale de la Baie. Spécialisée dans le traitement et la prévention des troubles musculo-squelettiques." />
          <meta property="og:image" content={`${siteUrl}/images/logo.jpeg`} />
          <meta property="og:url" content="https://andrea-pot-osteopathe.vercel.app/localisation" />
      </Head>
      <ThemeRegistry>
        <body>
          <Navbar/>
            {children}
          <Footer/>
        </body>
      </ThemeRegistry>
    </html>
  );
}
